accoj/blueprints/auth.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/1/19 20:55
# @Author  : Coodyz
# @Site    : https://github.com/coolbreeze2
# @File    : auth.py
# @Software: PyCharm
from flask import Blueprint, jsonify, request, session, redirect, render_template
from werkzeug.security import generate_password_hash, check_password_hash
from accoj.extensions import mongo
from accoj.utils import login_required
import re
import random
import datetime

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/signin', methods=['POST', 'GET'])
def signin():
    if request.method == "POST":
        form = request.form
        student_no = form.get("studentid")
        password = form.get("password")

        if student_no == "" or password == "":
            message = "请确保账号密码填写不为空"
            return jsonify(result="false", message="{}".format(message))
        else:
            user = mongo.db.user.find_one({"student_no": student_no})
            if user is None:
                message = "用户不存在"
                return jsonify(result="false", message="{}".format(message))
            user_password = user["password"]
            class_name = user["student_school"] + "-" + user["student_class"]
            if check_password_hash(user_password, password):
                role = user.get("role")
                session["student_name"] = user.get("student_name")
                session["nick_name"] = user.get("nick_name")
                session["role"] = role
                session["school_name"] = user.get("student_school")
                session["class_name"] = class_name
                session["teacher"] = user.get("teacher")
                session["team_no"] = user.get("team_no")
                session["member_no"] = student_no
                if role == "student" and (user.get("team_no") and user.get("team_no") != ""):
                    session["username"] = user.get("team_no")
                    permission = mongo.db.team.find_one({"team_no": session.get("username")},
                                                        {"_id": 0, "permission.{}_permission"
                                                        .format(session.get("member_no")): 1})
                    session["permission"] = permission.get("permission") if permission else None
                else:
                    session["username"] = student_no
                return jsonify(result="true")
            else:
                message = "密码错误"
                return jsonify(result="false", message="{}".format(message))
    return redirect("/")


"""
@auth_bp.route('/login', methods=['POST', 'GET'])
def login():
    myreg = re.compile(r'\w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}')
    if request.method == "POST":
        form = request.form
        student_no = form.get("studentid")
        email = form.get("email")
        student_faculty = form.get("login_faculty")
        student_class = form.get("login_class")
        password = form.get("password")
        password_again = form.get("password_again")
        vcode = form.get("vcode").lower()

        test_email = re.match(myreg, email)
        mail = dict(email="{}".format(email))
        right_email = mongo.db.other.find_one(mail)

        if student_no is "" or email is "" or student_faculty is "" \
                or student_class is "" or password is "" or password_again is "":
            message = "请确保注册信息填写完整"
            return jsonify(result="false", message="{}".format(message))
        else:
            user = mongo.db.user.find_one({"student_no": student_no})
            exit_email = mongo.db.user.find_one({"email": email})
            if user:
                message = "用户已存在"
                return jsonify(result="false", message="{}".format(message))
            elif exit_email:
                message = "密保邮箱已被使用"
                return jsonify(result="false", message="{}".format(message))
            elif password != password_again:
                message = "请确保两次密码一致"
                return jsonify(result="false", message="{}".format(message))
            elif len(student_no) != 11:
                message = "请确认学号格式正确"
                return jsonify(result="false", message="{}".format(message))
            elif test_email is None:
                message = "请确保邮箱填写正确"
                return jsonify(result="false", message="{}".format(message))
            elif not right_email:
                message = "该验证码失效或邮箱已更改"
                return jsonify(result="false", message="{}".format(message))
            elif vcode != right_email['VCode']:
                message = "请输入正确的验证码"
                return jsonify(result="false", message="{}".format(message))
            else:
                role = "student"
                session["username"] = student_no
                session["role"] = role
                post = dict(student_no="{}".format(student_no),
                            role=role,
                            student_name="",
                            teacher="teacher",
                            nick_name="",
                            student_school="",
                            personalized_signature="",
                            student_faculty="{}".format(student_faculty),
                            student_class="{}".format(student_class),
                            student_phone="",
                            student_sex="",
                            student_borth="",
                            password="{}".format(generate_password_hash(password)),
                            email="{}".format(email),
                            company_ids=[])
                mongo.db.user.insert_one(post)
                return jsonify(result="true")
    return redirect("/")
"""


@auth_bp.route('/logout')
def logout():
    session.clear()
    return redirect('/')


@auth_bp.route('/update_password', methods=['POST', 'GET'])
@login_required
def update_password():
    if request.method == "POST":
        form = request.form
        origin_pwd = form["origin_pwd"]
        new_pwd = form["new_pwd"]
        new_pwd_again = form["new_pwd_again"]
        if origin_pwd == "" or new_pwd == "" or new_pwd_again == "":
            message = "请确保信息填写完整"
            return jsonify(result="false", message="{}".format(message))
        else:
            user = mongo.db.user.find_one({"student_no": session["username"]})
            user_password = user["password"]
            if check_password_hash(user_password, origin_pwd) is False:
                message = "原密码错误"
                return jsonify(result="false", message="{}".format(message))
            else:
                if new_pwd != new_pwd_again:
                    message = "新密码与确认密码不一致"
                    return jsonify(result="false", message="{}".format(message))
                elif check_password_hash(user_password, new_pwd):
                    message = "新密码不能与原密码相同"
                    return jsonify(result="false", message="{}".format(message))
                else:
                    mongo.db.user.update_one({"student_no": session["username"]},
                                             {"$set": {"password": generate_password_hash(new_pwd)}})
                    session.clear()
                    return jsonify(result="true")

    return redirect('/')


@auth_bp.route('/VCode', methods=['GET', 'POST'])
def check_email():
    if request.method == "POST":
        form = request.form
        email = form.get("email")
        mail_random = ''
        for i in range(6):
            index = random.randrange(0, 3)
            if index != i:
                mail_random += str(random.randint(1, 9))
            elif index + 1 == i:
                mail_random += chr(random.randint(97, 122))
            else:
                mail_random += chr(random.randint(97, 122))
        mail = dict(email="{}".format(email))
        mongo.db.other.create_index("time", expireAfterSeconds=120)
        try:
            from accoj.emails import async_send_mail
            async_send_mail.delay(email, mail_random, 0, 0)
            if mongo.db.other.find_one(mail):
                temp = {
                    "time" : datetime.datetime.utcnow(),
                    "VCode": mail_random
                }
                mongo.db.other.update(mail, {"$set": temp})
                return jsonify(result="true")
            else:
                data = {
                    "email": email,
                    "time" : datetime.datetime.utcnow(),
                    "VCode": mail_random
                }
                mongo.db.other.insert_one(data)
                return jsonify(result="true")
        except Exception:
            return jsonify(result="false")
    return redirect("/")


@auth_bp.route('/findpsw', methods=['GET', 'POST'])
def find_password():
    if request.method == "POST":
        form = request.form
        student_no = form.get("studentid")
        email = form.get("email")
        vcode = form.get("vcode").lower()

        user = mongo.db.user.find_one({"student_no": student_no})
        stu = dict(student_no="{}".format(student_no))
        mail = dict(email="{}".format(email))
        if student_no == "":
            message = "学号不能为空"
            return jsonify(result="false", message=message)
        if email == "":
            message = "邮箱不能为空"
            return jsonify(result="false", message=message)
        if not user:
            message = "该用户不存在"
            return jsonify(result="false", message=message)
        else:
            find = mongo.db.user.find_one(stu)
            right = mongo.db.other.find_one(mail, {"VCode": 1})
            if not find["email"]:
                message = "该邮箱没有被注册"

accoj/blueprints/teacher.py
"""
教师后台管理
"""

import json
from flask import (session,
                   Blueprint,
                   render_template,
                   redirect,
                   url_for,
                   jsonify)
from accoj.extensions import redis_cli
from accoj.utils import login_required_teacher

teacher_bp = Blueprint("teacher", __name__)


@teacher_bp.route('/index', methods=['GET'])
def index():
    """
    个人信息
    """
    return render_template('teacher/index.html')


@teacher_bp.route('/message_system', methods=['GET'])
def message_system():
    """
    系统通知
    """
    return render_template('teacher/message_system.html')


@teacher_bp.route('/message_whisper', methods=['GET'])
def message_whisper():
    """
    消息面板
    """
    return render_template('teacher/message_whisper.html')


@teacher_bp.route('/add_class', methods=['GET'])
def add_class():
    """
    添加班级
    """
    return render_template('teacher/add-class.html')


@teacher_bp.route('/manage_time', methods=['GET'])
def manage_time():
    """
    时间管理
    """
    return render_template('teacher/manage-time.html')


@teacher_bp.route('/teacher_correct', methods=['GET'])
def teacher_correct():
    """
    批改作业
    """
    return render_template('teacher/teacher-correct.html')


@teacher_bp.route('/restart_course', methods=['GET'])
def restart_course():
    """
    课程重做
    """
    return render_template('teacher/restart-course.html')


@teacher_bp.route('/teacher_notify_c', methods=['GET'])
def teacher_notify_c():
    """
    发送通知(班级通知)
    """
    return render_template('teacher/teacher-notify-c.html')


@teacher_bp.route('/teacher_notify_p', methods=['GET'])
def teacher_notify_p():
    """
    发送通知(个人通知)
    """
    return render_template('teacher/teacher-notify-p.html')


@teacher_bp.route('/rank', methods=['GET'])
def rank():
    """
    排行榜
    """
    return render_template('teacher/rank.html')


@teacher_bp.route('/get_class_list', methods=['GET'])
def get_class_list():
    """获取班级列表"""
    teacher = session.get("username")
    user_info = redis_cli.lrange("user_info", 0, -1)
    user_info_len = len(user_info)
    for i in range(0, user_info_len):
        user_info[i] = json.loads(user_info[i])
        user_info[i].update({"num": i + 1})
    user_info = list(filter(lambda u: u.get("teacher") == teacher, user_info))
    result, data = True, user_info
    return jsonify(result=result, data=data)


@teacher_bp.route('/team', methods=['GET'])
def team():
    return render_template('teacher/team.html')


@teacher_bp.before_request
@login_required_teacher
def teacher_bp_before_request():
    """
    请求前钩子函数（局部）
    """
    role = session.get("role")
    if role == 'admin':
        return redirect(url_for('admin.index'))
    elif role == 'dbadmin':
        return redirect(url_for('dbadmin.index'))

accoj/templates/teacher/message_system.html
{% extends 'teacher/teacher-base.html' %}
{% block page_title %}系统通知{% endblock %}
{% block page_title_li %}<li class="active">系统通知</li>{% endblock %}
{% block content %}
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">系统通知</strong>
                    </div>
                    <div class="card-body">
                        <div class="msg">
                            <div class="friend-message">
                                <div class="title">
                                    系统通知
                                </div>
                                <div data-message-box class="message-box">
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <link rel="stylesheet" href="http://cdn.accoj.top/static/accoj-1.0.0/message_whisper.css">
    <script src="http://cdn.accoj.top/static/accoj-1.0.0/message_system.js"></script>

{% endblock %}

accoj/templates/teacher/message_whisper.html
{% extends 'teacher/teacher-base.html' %}
{% block page_title %}我的消息{% endblock %}
{% block page_title_li %}我的消息{% endblock %}
{% block content %}
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">我的消息</strong>
                    </div>
                    <div class="card-body">
                        <div class="msg">
                            <div class="friend-list">
                                <div class="title">
                                    班级
                                </div>
                                <div id="room-list" class="list">
                                </div>
                            </div>
                            <div class="friend-message">
                                <div id="room-name" class="title">

                                </div>
                                <div id="message-box" class="message-box">

                                </div>
                                <div class="send-box">
                                    <textarea id="message-content" placeholder="输入消息..."></textarea>
                                    <div>
                                        <div>
                                            <span id="now-words">0</span>
                                            <span>/</span>
                                            <span>200</span>
                                        </div>
                                        <button data-send-message>发送</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <link rel="stylesheet" href="http://cdn.accoj.top/static/accoj-1.0.0/message_whisper.css">
    <script src="{{ url_for('static', filename='js/message_whisper.js') }}"></script>
{% endblock %}

accoj/templates/teacher/teacher-base.html
<!doctype html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>ACCOJ - 教师后台</title>
    <!-- Shortcut icon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/logo.png') }}">
    <!-- Styles -->
    <link href="http://cdn.accoj.top/static/cdn/8.0.0.normalize.css" rel="stylesheet">
    <link href="http://cdn.accoj.top/static/cdn/4.1.3.bootstrap.css" rel="stylesheet">
    <link href="http://cdn.accoj.top/static/cdn/4.7.0.font-awesome.css" rel="stylesheet">
    <link href="http://cdn.accoj.top/static/cdn/0.1.2.themify-icons.css" rel="stylesheet">
    <link href="http://cdn.accoj.top/static/cdn/1.2.3.pe-icon-7-stroke.css" rel="stylesheet">
    <link href="http://cdn.accoj.top/static/cdn/3.2.0.flag-icon.css" rel="stylesheet">


    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <link href="http://cdn.accoj.top/static/cdn/back-stage/style.css" rel="stylesheet">
    <link href="http://cdn.accoj.top/static/cdn/back-stage/base.css" rel="stylesheet">
    <link href="http://cdn.accoj.top/static/cdn/back-stage/cs-skin-elastic.css" rel="stylesheet">
    <!-- Scripts -->
    <script src="http://cdn.accoj.top/static/cdn/2.7.2.Chart.js" charset="UTF-8"></script>
    <script src="http://cdn.accoj.top/static/cdn/0.7.0.chartjs-plugin-datalabels.js" charset="UTF-8"></script>
    <script src="http://cdn.accoj.top/static/cdn/2.3.0.socket.io.js" charset="UTF-8"></script>
    <script src="http://cdn.accoj.top/static/cdn/2.2.4.jquery.js" charset="UTF-8"></script>
    <script src="http://cdn.accoj.top/static/cdn/3.5.1.jquery.js" charset="UTF-8"></script>
    <script src="http://cdn.accoj.top/static/cdn/1.14.4.popper.js" charset="UTF-8"></script>
    <script src="http://cdn.accoj.top/static/cdn/4.1.3.bootstrap.js" charset="UTF-8"></script>
    <script src="http://cdn.accoj.top/static/cdn/0.7.2.matchHeight.js" charset="UTF-8"></script>

    <script src="http://cdn.accoj.top/static/cdn/back-stage/main.js" charset="UTF-8"></script>
    <script src="{{ url_for('static', filename='js/profile-base.js') }}" charset="UTF-8"></script>
    <script type="text/javascript" charset="UTF-8">
        function get_csrf_token() {
            return "{{ csrf_token() }}";
        }

        function get_current_user_id() {
            return "{{ username }}";
        }
    </script>
</head>
<body>
<!-- Left Panel -->

<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">

        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a><i class="menu-icon fa fa-laptop"></i>教师后台 </a>
                </li>
                <li class="menu-title">
                    <hr>
                </li><!-- /.menu-title -->
                <li>
                    <a href="{{ url_for('teacher.index') }}"><i class="menu-icon fa fa-user"></i>个人信息 </a>
                </li>
                <li>
                    <a href="{{ url_for('teacher.message_system') }}"><i class="menu-icon fa fa-bell-o"></i>系统通知 </a>
                </li>
                <li>
                    <a href="{{ url_for('teacher.message_whisper') }}"><i class="menu-icon fa fa-envelope"></i>我的消息 </a>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false"> <i class="menu-icon fa fa-table"></i>班级管理</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-square"></i><a href="{{ url_for('teacher.add_class') }}"> 添加班级</a></li>
                        <li><i class="fa fa-clock-o"></i><a href="{{ url_for('teacher.manage_time') }}"> 课程时间</a></li>
                        <li><i class="fa fa-life-bouy"></i><a href="{{ url_for('teacher.restart_course') }}"> 题目重做</a>
                        </li>
                        <li><i class="fa fa-users"></i><a href="{{ url_for('teacher.team') }}"> 小组管理</a></li>
                    </ul>
                </li>

                <li>
                    <a href="{{ url_for('teacher.teacher_correct') }}"> <i class="menu-icon fa fa-pencil"></i>批改作业</a>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false"> <i class="menu-icon fa fa-bell"></i>发送通知</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><a href="{{ url_for('teacher.teacher_notify_c') }}"><i class="fa fa-bell"></i>班级通知</a></li>
                        <li><a href="{{ url_for('teacher.teacher_notify_p') }}"><i class="fa fa-bell-o"></i>个人通知</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{{ url_for('teacher.rank') }}"><i class="menu-icon fa fa-bar-chart-o"></i>排行榜 </a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside><!-- /#left-panel -->

<!-- Left Panel -->

<!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">
        <div class="top-left">
            <div class="navbar-header">
                <a class="navbar-brand" href="/"><img src="{{ url_for('static', filename='img/logo1.png') }}"
                                                       alt="Logo"></a>
                <a class="navbar-brand hidden" href="/"><img src="{{ url_for('static', filename='img/logo2.png') }}"
                                                              alt="Logo"></a>
            </div>
        </div>
        <div class="top-right">
            <div class="header-menu">
                <div class="header-left">

                    <div class="dropdown for-notification">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="notification"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-bell"></i>
                            <span class="count bg-danger">3</span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="notification">
                            <p class="red">你有3条未读通知</p>
                            <a class="dropdown-item media" href="#">
                                <i class="fa fa-check"></i>
                                <p>Server #1 overloaded.</p>
                            </a>
                            <a class="dropdown-item media" href="#">
                                <i class="fa fa-info"></i>
                                <p>Server #2 overloaded.</p>
                            </a>
                            <a class="dropdown-item media" href="#">
                                <i class="fa fa-warning"></i>
                                <p>Server #3 overloaded.</p>
                            </a>
                        </div>
                    </div>

                    <div class="dropdown for-message">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="message"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-envelope"></i>
                            <span class="count bg-primary">4</span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="message">
                            <p class="red">你有4条未读消息</p>
                            <a class="dropdown-item media" href="#">
                                <span class="photo media-left"><img alt="avatar" src="{{ url_for('static', filename='img/avatar/1.jpg') }}"></span>
                                <div class="message media-body">
                                    <span class="name float-left">Jonathan Smith</span>
                                    <span class="time float-right">Just now</span>
                                    <p>Hello, this is an example msg</p>
                                </div>
                            </a>
                            <a class="dropdown-item media" href="#">
                                <span class="photo media-left"><img alt="avatar" src="{{ url_for('static', filename='img/avatar/2.jpg') }}"></span>
                                <div class="message media-body">
                                    <span class="name float-left">Jack Sanders</span>
                                    <span class="time float-right">5 minutes ago</span>
                                    <p>Lorem ipsum dolor sit amet, consectetur</p>
                                </div>
                            </a>
                            <a class="dropdown-item media" href="#">
                                <span class="photo media-left"><img alt="avatar" src="{{ url_for('static', filename='img/avatar/3.jpg') }}"></span>
                                <div class="message media-body">
                                    <span class="name float-left">Cheryl Wheeler</span>
                                    <span class="time float-right">10 minutes ago</span>
                                    <p>Hello, this is an example msg</p>
                                </div>
                            </a>
                            <a class="dropdown-item media" href="#">
                                <span class="photo media-left"><img alt="avatar" src="{{ url_for('static', filename='img/avatar/4.jpg') }}"></span>
                                <div class="message media-body">
                                    <span class="name float-left">Rachel Santos</span>
                                    <span class="time float-right">15 minutes ago</span>
                                    <p>Lorem ipsum dolor sit amet, consectetur</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="user-area dropdown float-right">
                    <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        <img class="user-avatar rounded-circle" src="{{ url_for('static', filename='img/admin.jpg') }}"
                             alt="User Avatar">
                    </a>

                    <div class="user-menu dropdown-menu">
                        <a class="nav-link" href="{{ url_for('teacher.index') }}"><i class="fa fa- user"></i>个人中心</a>

                        <a class="nav-link" href="#"><i class="fa fa- user"></i>通知 <span class="count">13</span></a>

                        <a class="nav-link" href="{{ url_for('auth.logout') }}"><i class="fa fa-power -off"></i>注销</a>
                    </div>
                </div>

            </div>
        </div>
    </header><!-- /header -->
    <!-- Header-->

    <div class="breadcrumbs">
        <div class="breadcrumbs-inner">
            <div class="row m-0">
                <div class="col-sm-4">
                    <div class="page-header float-left">
                        <div class="page-title">
                            <h1>{% block page_title %}{% endblock %}</h1>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="page-header float-right">
                        <div class="page-title">
                            <ol class="breadcrumb text-right">
                                <li><a href="#">教师后台</a></li>
                                {% block page_title_li %}{% endblock %}
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="content">
        {% block content %}{% endblock %}
    </div><!-- .content -->

    <div class="clearfix"></div>
    <!-- Footer -->
    <footer class="site-footer">
        <div class="footer-inner bg-white">
            <div class="row">
                <div class="col-sm-6">
                    Copyright © 2019-2020 <a href="http://pointerlabs.org">PointerLabs</a>.
                    All Rights Reserved.
                </div>
                <div class="col-sm-6 text-right">
                    Designed by 指针实验室&nbsp;PointerLabs
                </div>
            </div>
        </div>
    </footer>
    <!-- /.site-footer -->

</div><!-- /#right-panel -->


</body>
</html>