accoj/blueprints/accoj.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/1/19 20:55
# @Author  : Coodyz
# @Site    : https://github.com/coolbreeze2
# @File    : accoj.py
# @Software: PyCharm
from flask import (Blueprint,
                   render_template,
                   jsonify,
                   session,
                   redirect,
                   url_for)
from accoj.utils import (login_required,
                         complete_required1,
                         course_time_open_required,
                         course_time_not_end_required,
                         availability_of_the_team,
                         is_leader,
                         manage_exercises_permission, login_required_student)
from accoj.blueprints import submit_infos, get_data
from accoj.utils import (is_number,
                         limit_content_length,
                         update_business_rank_score)
from accoj.extensions import mongo
from accoj.deal_business.create_businesses import create_businesses
from accoj.deal_business import cal_answer
from flask import request

accoj_bp = Blueprint('accoj', __name__)
MAX_BUSINESS_NO = 20


# 第一次课程----start-------------------------------------------------------------------------------
@accoj_bp.route('/coursei', methods=['GET', 'POST'])
@availability_of_the_team
@course_time_open_required(1)
def coursei():
    """
    第一次课程
    """
    return render_template('course/coursei.html')


@accoj_bp.route('/get_company_info', methods=['POST'])
def get_company_info():
    """
    获取公司信息
    """
    company = mongo.db.company.find_one(dict(student_no=session.get("username")),
                                        dict(_id=0, com_name=1, com_address=1, com_business_addr=1,
                                             com_legal_rep=1,
                                             com_regist_cap=1, com_operate_period=1, com_business_scope=1,
                                             com_shareholder=1))
    # 公司已经创立过，填充表单
    if company:
        return jsonify(result=True, company_info=company)
    return jsonify(result=False, message="未知错误！")


@accoj_bp.route('/submit_company_info', methods=['POST'])
@is_leader
@course_time_not_end_required(1)
def submit_company_info():
    """
    提交公司创立信息表单
    """

    def get_schedule_dict(schedule_type):
        def format_key(t_key):
            return "{}_{}".format(t_key, schedule_type)

        return {format_key("business"): False,
                format_key("key_element"): [],
                format_key("subject"): [],
                format_key("entry"): [],
                format_key("ledger"): {format_key("ledger1"): [], format_key("ledger2"): []},
                format_key("balance_sheet"): False,
                format_key("acc_document"): [],
                format_key("subsidiary_account"): [],
                format_key("acc_balance_sheet"): False,
                format_key("new_balance_sheet"): False,
                format_key("profit_statement"): False,
                format_key("trend_analysis"): {"first": False, "second": False},
                format_key("common_ratio_analysis"): {"first": False, "second": False},
                format_key("ratio_analysis"): False,
                format_key("dupont_analysis"): False, }

    company = mongo.db.company.find_one({"student_no": session.get("username")})
    if company is not None:
        return jsonify(result=False, message="已经创立过公司！")
    json_data = request.get_json()
    data_list = ["com_name", "com_address", "com_business_addr", "com_legal_rep", "com_regist_cap",
                 "com_operate_period", "com_business_scope", "com_shareholder_1", "com_shareholder_2",
                 "com_shareholder_3", "com_shareholder_4", "com_shareholder_5"]
    data_dict = dict()
    data_dict["com_shareholder"] = []
    err_pos = []

    data_dict["student_no"] = session.get("username")
    for data_name in data_list:
        data_dict[data_name] = json_data.get(data_name)

    flag = True
    shareholder_num = 0
    for key, value in data_dict.items():
        if not value and key != "com_shareholder":
            if not key.startswith("com_shareholder_"):
                flag = False
                err_pos.append({"err_pos": key})
            else:
                shareholder_num += 1
                if key == "com_shareholder_1":
                    err_pos.append({"err_pos": key})
        else:
            if key.startswith("com_shareholder_"):
                shareholder_num += 1
                data_dict["com_shareholder"].append(value)
            elif key == "com_operate_period":
                if not is_number(value):
                    flag = False
                    err_pos.append({"err_pos": key})
                else:
                    value = float(value)
                    if value < 5 or value > 500:
                        flag = False
                        err_pos.append({"err_pos": key})
            elif key == "com_regist_cap":
                if not is_number(value):
                    flag = False
                    err_pos.append({"err_pos": key})
                else:
                    value = float(value)
                    if value < 100 or value > 1000:
                        flag = False
                        err_pos.append({"err_pos": key})

    if not shareholder_num:
        flag = False
    if not flag:
        return jsonify(result=False, err_pos=err_pos, message="信息未填写完整或信息填写格式错误！")
    else:
        for key in list(data_dict.keys()):
            if key.startswith("com_shareholder_"):
                data_dict.pop(key)
            elif key == "com_regist_cap" or key == "com_operate_period":
                data_dict[key] = float(data_dict[key])
        data_dict["com_bank_savings"] = data_dict["com_regist_cap"] * 10000
        data_dict.update(dict(com_cash=0, business_num=0))

        schedule_confirm = get_schedule_dict("confirm")
        schedule_saved = get_schedule_dict("saved")

        data_dict.update(dict(schedule_confirm=schedule_confirm,
                              schedule_saved=schedule_saved,
                              com_assets=[],
                              businesses=[],
                              key_element_infos=[],
                              subject_infos=[],
                              entry_infos=[],
                              acc_document_infos=[]))
        data_dict_cp = data_dict.copy()
        # 副本公司同时创建
        data_dict_cp["student_no"] = "{}_cp".format(data_dict["student_no"])
        mongo.db.company.insert_many([data_dict, data_dict_cp])
        return jsonify(result=True, message="公司创建成功！")


@accoj_bp.route('/submit_business_info', methods=['POST'])
@is_leader
@course_time_not_end_required(1)
def submit_business_info():
    """
    提交业务内容信息，提交成功后不可修改
    """
    company = mongo.db.company.find_one(dict(student_no="{}".format(session.get("username"))),
                                        dict(businesses=1, business_num=1, schedule_confirm=1, _id=0, ))
    if not company:
        return jsonify(result=False, message="公司未创立")
    schedule_confirm = company.get("schedule_confirm")
    businesses = company.get("businesses")
    business_confirm = schedule_confirm.get("business_confirm")

    if len(businesses) == 0:
        return jsonify(result=False, message="未生成业务！")

    if not business_confirm:
        cal_answer()  # 计算答案

        company_cp = mongo.db.company.find_one(dict(student_no="{}_cp".format(session.get("username"))),
                                               dict(ledger_infos=1, _id=0))
        ledger_infos = company_cp.get("ledger_infos")
        ledger_infos_1 = ledger_infos.get("ledger_infos_1")
        ledger_infos_2 = ledger_infos.get("ledger_infos_2")
        subjects_tmp1 = [key for key in ledger_infos_1]
        subjects_tmp2 = [key for key in ledger_infos_2]

        involve_subjects = dict(involve_subjects_1=subjects_tmp1, involve_subjects_2=subjects_tmp2)
        # 完成第一模块， 分配组队题目权限
        manage_exercises_permission(team_no=session.get("username"))
        mongo.db.company.update({"student_no": {"$regex": r"^{}".format(session.get("username"))}},
                                {"$set": {"schedule_confirm.business_confirm": True,
                                          "involve_subjects": involve_subjects}},
                                multi=True)
        # 更新成绩进排行榜集合
        update_business_rank_score()
        # session 注入permission
        permission = mongo.db.team.find_one({"team_no": session.get("username")},
                                            {"_id": 0, "permission.{}_permission"
                                            .format(session.get("member_no")): 1})
        session["permission"] = permission.get("permission") if permission else None

        return jsonify(result=True)
    else:
        return jsonify(result=False, message="已经提交过！")


@accoj_bp.route('/get_business_info', methods=['POST'])
def get_business_info():
    """
    获取业务内容信息
    """
    username = session.get("username")
    company = mongo.db.company.find_one(dict(student_no="{}".format(username)),
                                        dict(businesses=1, schedule_confirm=1, _id=0))
    if company:
        schedule_confirm = company.get("schedule_confirm")
        confirmed = schedule_confirm.get("business_confirm")
        businesses = company.get("businesses")
        businesses = businesses if businesses else None
        return jsonify(result=True, businesses=businesses, confirmed=confirmed)
    else:
        return jsonify(result=False, message="公司未创立！")


@accoj_bp.route('/create_business', methods=['POST'])
@is_leader
@course_time_not_end_required(1)
def create_business():
    """
    生成业务
    """
    result, message = False, "公司未创立！"
    username = session.get("username")
    company = mongo.db.company.find_one({"student_no": "{}".format(username)})
    if not company:
        return jsonify(result=result, message=message)

accoj/blueprints/index.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/2/18 15:43
# @Author  : Coodyz
# @Site    : https://github.com/coolbreeze2
# @File    : index.py
# @Software: PyCharm
from flask import Blueprint, render_template, request
from accoj.extensions import mongo
import re

index_bp = Blueprint('index', __name__)


@index_bp.route('/', methods=['POST', 'GET'])
def index():
    return render_template('index.html')


@index_bp.route('/about', methods=['POST', 'GET'])
def about():
    return render_template('about.html')


@index_bp.route('/notice', methods=['POST', 'GET'])
def notice():
    count = request.args.get("count", type=int)
    notice = list(mongo.db.notice.find().sort([("is_topping", -1), ("timestamp", -1)]))

    if notice and type(count) == int and count < len(notice):
        subject = notice[count]["subject"]
        notice_time = notice[count]["timestamp"]
        text = notice[count]["text"]
        notice_time = notice_time[0:4] + "年" + notice_time[5:7] + "月" + notice_time[8:10] + "日"
        result = re.split(r"  {2,}|\t", text)
        content = "<p style=\"text-indent:30px \">"
        for index, value in enumerate(result):
            if result[0] == '':
                result[0]="ENDOF"
                continue
            elif index != len(result) - 1:
                content += result[index] + "</p><p style=\"text-indent:30px;font-size=18px\">"
            else:
                content += result[index] + "</p>"

        return render_template('notice.html', subject=subject, notice_time=notice_time, text=content)
    return render_template("errors/404.html")

accoj/blueprints/teacher.py
"""
教师后台管理
"""

import json
from flask import (session,
                   Blueprint,
                   render_template,
                   redirect,
                   url_for,
                   jsonify)
from accoj.extensions import redis_cli
from accoj.utils import login_required_teacher

teacher_bp = Blueprint("teacher", __name__)


@teacher_bp.route('/index', methods=['GET'])
def index():
    """
    个人信息
    """
    return render_template('teacher/index.html')


@teacher_bp.route('/message_system', methods=['GET'])
def message_system():
    """
    系统通知
    """
    return render_template('teacher/message_system.html')


@teacher_bp.route('/message_whisper', methods=['GET'])
def message_whisper():
    """
    消息面板
    """
    return render_template('teacher/message_whisper.html')


@teacher_bp.route('/add_class', methods=['GET'])
def add_class():
    """
    添加班级
    """
    return render_template('teacher/add-class.html')


@teacher_bp.route('/manage_time', methods=['GET'])
def manage_time():
    """
    时间管理
    """
    return render_template('teacher/manage-time.html')


@teacher_bp.route('/teacher_correct', methods=['GET'])
def teacher_correct():
    """
    批改作业
    """
    return render_template('teacher/teacher-correct.html')


@teacher_bp.route('/restart_course', methods=['GET'])
def restart_course():
    """
    课程重做
    """
    return render_template('teacher/restart-course.html')


@teacher_bp.route('/teacher_notify_c', methods=['GET'])
def teacher_notify_c():
    """
    发送通知(班级通知)
    """
    return render_template('teacher/teacher-notify-c.html')


@teacher_bp.route('/teacher_notify_p', methods=['GET'])
def teacher_notify_p():
    """
    发送通知(个人通知)
    """
    return render_template('teacher/teacher-notify-p.html')


@teacher_bp.route('/rank', methods=['GET'])
def rank():
    """
    排行榜
    """
    return render_template('teacher/rank.html')


@teacher_bp.route('/get_class_list', methods=['GET'])
def get_class_list():
    """获取班级列表"""
    teacher = session.get("username")
    user_info = redis_cli.lrange("user_info", 0, -1)
    user_info_len = len(user_info)
    for i in range(0, user_info_len):
        user_info[i] = json.loads(user_info[i])
        user_info[i].update({"num": i + 1})
    user_info = list(filter(lambda u: u.get("teacher") == teacher, user_info))
    result, data = True, user_info
    return jsonify(result=result, data=data)


@teacher_bp.route('/team', methods=['GET'])
def team():
    return render_template('teacher/team.html')


@teacher_bp.before_request
@login_required_teacher
def teacher_bp_before_request():
    """
    请求前钩子函数（局部）
    """
    role = session.get("role")
    if role == 'admin':
        return redirect(url_for('admin.index'))
    elif role == 'dbadmin':
        return redirect(url_for('dbadmin.index'))

accoj/templates/course/courseBase.html
{% extends 'base.html' %}

{% block meun %}
    <!-- 习题菜单 -->
    <div>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#menu" aria-expanded="false">
                        <span class="sr-only"></span> <span class="icon-bar"></span> <span
                            class="icon-bar"></span> <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="menu">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('accoj.coursei') }}" data-toggle="tooltip"
                               data-placement="bottom" title="已开放">I.会计主体</a></li>
                        <li><a href="{{ url_for('accoj.courseii') }}" data-toggle="tooltip"
                               data-placement="bottom" title="已开放">II.会计要素</a></li>
                        <li><a href="{{ url_for('accoj.courseiii') }}" data-toggle="tooltip"
                               data-placement="bottom" title="已开放">III.会计科目</a></li>
                        <li><a href="{{ url_for('accoj.courseiv') }}" data-toggle="tooltip"
                               data-placement="bottom" title="已开放">IV.会计分录</a></li>
                        <li><a href="{{ url_for('accoj.coursev') }}" data-toggle="tooltip"
                               data-placement="bottom" title="已开放">V.会计账户</a></li>
                        <li><a href="{{ url_for('accoj.coursevi') }}" data-toggle="tooltip"
                               data-placement="bottom" title="已开放">VI.会计凭证</a></li>
                        <li><a href="{{ url_for('accoj.coursevii') }}" data-toggle="tooltip"
                               data-placement="bottom" title="已开放">VII.会计账簿</a></li>
                        <li><a href="{{ url_for('accoj.courseviii') }}" data-toggle="tooltip"
                               data-placement="bottom" title="已开放">VIII.会计报表</a></li>
                        <li><a href="{{ url_for('accoj.courseix') }}" data-toggle="tooltip"
                               data-placement="bottom" title="已开放">IX.会计报表分析</a></li>
                        <li><a href="{{ url_for('accoj.coursex') }}" data-toggle="tooltip"
                               data-placement="bottom" title="已开放">X.会计报告</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% if role == "教师" %}
            <div id="correct" class="sideBox">
                <a href="{{ url_for('teacher.teacher_correct') }}">
                    <i class="fa fa-pencil-square-o " aria-hidden="true"></i>
                </a>


                <div class="sideBox-tips">
                    <span>批改作业</span>
                </div>
            </div>
        {% endif %}
        {% if role == "学生" %}
            <div id="redo" class="sideBox">
                <a>
                    <i class="fa fa-eraser " aria-hidden="true"></i>
                </a>


                <div class="sideBox-tips">
                    <span>申请重做</span>
                </div>
            </div>

            <div class="modal fade" id='redoModel' tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">申请重做</h4>
                        </div>
                        <div class="modal-body">
                            <form id="redo_info">
                                <div class="form-group">
                                    <!-- <label for="courseSelect">选择课程：</label>
                                    <select id="courseSelect" class="form-control" name="course_no"
                                           width='100px'>
                                           <option name="2" value="2">第二次课程</option>
                                           <option name="3" value="3">第三次课程</option>
                                           <option name="4" value="4">第四次课程</option>
                                           <option name="5" value="5">第五次课程</option>
                                           <option name="6" value="6">第六次课程</option>
                                           <option name="7" value="7">第七次课程</option>
                                           <option name="8" value="8">第八次课程</option>
                                           <option name="9" value="9">第九次课程</option>
                                           <option name="10" value="10">第十次课程</option>
                                    </select> -->
                                </div>
                                <div class="form-group">
                                    <label for="reasonInput">申请原因：</label>
                                    <textarea class="form-control" id="reasonInput" rows="3" name=reason
                                              style="max-width: 568px;"></textarea>
                                </div>


                            </form>

                        </div>
                        <div class="modal-footer">
                            <div id='redo_message'>
                            </div>
                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                            <button type="button" data-submit-redo class="btn btn-primary">提交申请</button>
                        </div>
                        <div id='message_box'></div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
            <!-- 信息提示框 -->

        {% endif %}


    </div>
{% endblock meun %}

{% block title %}会计实训系统 实训{% endblock title %}

accoj/templates/course/courseiv.html
{% extends 'course/courseBase.html' %}
{% block courseBody %}
<!-- courseiv css -->
<link href="http://cdn.accoj.top/static/accoj-1.0.0/courseiv.css"
      rel="stylesheet">
<script src="{{url_for('static', filename='js/course/courseiv.js')}}" charset="UTF-8"></script>
    <!--第四次课程-->
    <div class="courseBody">
        <!-- 习题主体 -->
        <div class="container">
            <div class="panel panel-default">
                <!--作业要求-->
                <div class="panel-heading">
				<span>1、掌握借贷记账法的原理：包括账户结构、记账规则、会计分录编写规范。<br/> 2、理解并运用常用会计科目。
				</span>
                    </br>
                    <strong>3、你需要完成的题目有：</strong><strong id="selfQuestion"></strong>
                </div>
                <div class="panel-body">
                    <div class="acc-pn-center">
                        <nav aria-label="Page navigation">
                            <ul data-page class="pagination">
                                <li data-page-control><a aria-hidden="true">&laquo;</a></li>
                                <li data-page-control><a aria-hidden="true">‹</a></li>
                                <li data-page-control class="active"><a>1</a></li>
                                <li data-page-control><a>2</a></li>
                                <li data-page-control><a>3</a></li>
                                <li data-page-control><a>4</a></li>
                                <li data-page-control><a>5</a></li>
                                <li data-page-control><a aria-hidden="true">›</a></li>
                                <li data-page-control><a aria-hidden="true">&raquo;</a></li>
                            </ul>
                        </nav>
                    </div>
                    <hr class="simple"/>
                    <p class="help-block">温馨提示：
                    <p class="help-block">1.完成当前业务信息后应手动保存，防止信息丢失。</p>
                    <p class="help-block">2.提交前确保所有题目已保存，防止丢分。</p>

                    <em class="acc-score-help">&nbsp;/&nbsp;总得分</em>
                    <em class="acc-score-help">当前</em>
                    </p>
                    <h4>
                        <span class="glyphicon glyphicon-bookmark"></span> <em id="em_no"></em>
                        <span id="submit_status_span" class="glyphicon glyphicon-ok acc-completed">已完成</span>
                        <em data-total-score></em>
                        <em data-now-score></em>
                    </h4>
                    <div class="acc-container-answer">
                        <blockquote>
                            <label id="business_type" class="label label-success"></label>
                            <p id="business_content"></p>
                        </blockquote>
                    </div>
                    <div class="acc-container-answer">
                        <div>
                            <p class="acc-title">填写完整分录</p>
                            <table class="table table-bordered acc-unborder">
                                <tbody>
                                <tr class="acc-table-format-4-1">
                                    <th class="acc-unedit">借：</th>
                                <td class="acc-unedit"></td>
                                <td>
                                    <label>
                                        <input type="text" name="subject" data-illegal-char
                                               id="subject1" placeholder="科目">
                                    </label>
                                </td>
                                <td>
                                    <label>
                                        <input type="text" name="money" id="money1" placeholder="0.0" data-real-number>
                                    </label>
                                </td>
                                <td>
                                    <div class="acc-plus">
                                        <a type="button" class="btn" data-iv-addRow-1 data-toggle="tooltip" data-placement="left" title="增加行">
                                            <span class="glyphicon glyphicon-plus-sign"></span>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <tr id="borrowRowAfter" class="acc-table-format-4-1">
                                <td class="acc-unedit"></td>
                                <th class="acc-unedit">贷：</th>
                                <td>
                                    <label>
                                        <input type="text" name="subject" data-illegal-char id="subject0" placeholder="科目">
                                    </label>
                                </td>
                                <td>
                                    <label>
                                        <input type="text" name="money" id="money0" placeholder="0.0" data-real-number>
                                    </label>
                                </td>
                                <td>
                                    <div class="acc-plus">
                                        <a type="button" class="btn" data-iv-addRow-2 data-toggle="tooltip" data-placement="left" title="增加行">
                                            <span class="glyphicon glyphicon-plus-sign"></span>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                                <tr id="loanRowAfter"></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <hr class="simple"/>
                    <!--信息提示窗口-->
                    <div id="course_iv_message"></div>
                    <div class="acc-btn-left">
                        <button type="button" class="btn btn-info" data-answer>查看答案</button>
                    </div>
                    <div class="acc-btn-right">
                        <button class="btn btn-info" data-save type="button">
                            <span class="glyphicon"></span>保存
                        </button>
                        <button type="button" class="btn btn-success " data-toggle="tooltip" data-placement="top"
                                title="请保存所有题目再提交" data-confirm>
                            <span class="glyphicon"></span>提交
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 防尾前移 -->
    <div class="acc-container-separate"></div>

{% endblock courseBody %}

accoj/templates/course/notOpen.html
{% extends 'course/courseBase.html' %}
{% block courseBody %}
<h1 style="text-align: center">当前课程未开启!<a href="{{ url_for('index.index') }}"><br><br>返回首页</a></h1>
    <br
    <!-- 防尾前移 -->
    <div class="acc-container-separate"></div>

{% endblock courseBody %}

accoj/templates/course/notTeam.html
{% extends 'course/courseBase.html' %}
{% block courseBody %}
    <h1 style="text-align: center">未组队，无法进入!<a href="{{ url_for('index.index') }}"><br><br>返回首页</a></h1>
    <br>
    <!-- 防尾前移 -->
    <div class="acc-container-separate"></div>

{% endblock courseBody %}